### PR TITLE
release 1.1.0rc2

### PR DESCRIPTION
**Pull request by matthewhanson**
GeoLambda is now a runtime agnostic Docker image, but there is a Python example project.

On a merge to master:
- Docker image built and pushed to docker hub developmentseed/geolambda:${VERSION}
- Example python36 build Docker image built and pushed to developmentseed/geolambda:${VERSION}-python36
- Public Lambda layers are automatically deployed to us-east-1, us-west-2, and eu-central-1. They can be used with any Lambda runtime. See the README for the ARNs

### CODE REVIEW

**Comment by matthewhanson** [comment]
Thanks @vincentsarago , one thing I was wondering about is the http2 support. It seems to have built properly, but the nghttp2 library wasn't needed in the deploy package so I wasn't sure if it was included statically. 

What's the best way to test that http2 support is working?

**Comment by vincentsarago** [comment]
@matthewhanson 

```bash
$ ldd libgdal.so | grep "http2"
	libnghttp2.so.14 => /usr/local/lib/libnghttp2.so.14 (0x00007fc219c2c000)
```
GDAL seems to be built correctly and will work for the lambda layer. For packaging, it will not work because AWS Lambda will fetch libcurl pre-installed in the image (AWS AMI) (ref: https://github.com/RemotePixel/amazonlinux-gdal/issues/7) 

To solve this we need to hardcode the libcurl path (and to other lib) inside goal shared lib but then it can makes things a bit difficult (I haven't find the way to make the hardcoded path relative).

**Comment by matthewhanson** [comment]
ah, read the issue, need to use rpath, ugh.

However, you should be able to set rpath to $ORIGIN which will look for the library in the same directory as the parent lib.

**Comment by vincentsarago** [comment]
@matthewhanson I tried to use `$ORIGIN` without success sadly but I'll put that on my unix skills being 👎

**Comment by matthewhanson** [comment]
changing this to a release candidate (1.1.0rc2) and merging
gdal updated to use rpath to find correct libraries included in the deployment package

**Pull request merged**
