### PR TITLE
release 2.1.0

### LINKED ISSUE #96: Update to GDAL > 3.1 for COG driver
Need a GDAL update to 3.1 or greater to get Cloud Optimized GeoTIFF generator (https://gdal.org/drivers/raster/cog.html).
I downloaded the repo and updated the dockerfile to what seems like works with updated gdal and other packages as well. Anyone want to give it a try?
[Dockerfile.txt](https://github.com/developmentseed/geolambda/files/5846017/Dockerfile.txt)

### PR DESCRIPTION
**Pull request by matthewhanson**
closes #96

### CODE REVIEW

**Comment by danielklim** [comment]
The build fails when building GDAL:
```
make[3]: Entering directory `/build/gdal/ogr/ogrsf_frmts/elastic'
g++ -std=c++11 -I/build/gdal/port -I/build/gdal/gcore -I/build/gdal/alg -I/build/gdal/ogr -I/build/gdal/ogr/ogrsf_frmts -I/build/gdal/gnm -I/build/gdal/apps -DHAVE_AVX_AT_COMPILE_TIME -DHAVE_SSSE3_AT_COMPILE_TIME -DHAVE_SSE_AT_COMPILE_TIME -O2 -Os -fPIC -fvisibility=hidden  -Wall -Wextra -Winit-self -Wunused-parameter -Wformat -Werror=format-security -Wno-format-nonliteral -Wlogical-op -Wshadow -Werror=vla -Wmissing-declarations -Wnon-virtual-dtor -Woverloaded-virtual -fno-operator-names -Wzero-as-null-pointer-constant  -I/build/gdal/ogr/ogrsf_frmts/geojson/libjson -I.. -I../.. -I../geojson -DGNM_ENABLED -I/build/gdal/port -I/usr/local/include -I/usr/local/include -I/usr/local -I/usr/local/include -I/usr/local/include -I/usr/local/include  -DGDAL_COMPILATION -c -o ../o/ogrelasticlayer.o ogrelasticlayer.cpp
In file included from ogr_elastic.h:33:0,
                 from ogrelasticlayer.cpp:30:
/build/gdal/ogr/ogrsf_frmts/ogrsf_frmts.h: In lambda function:
/build/gdal/ogr/ogrsf_frmts/ogrsf_frmts.h:109:18: error: ‘OGRErr OGRLayer::GetExtentInternal(int, OGREnvelope*, int)’ is protected
     OGRErr       GetExtentInternal(int iGeomField, OGREnvelope *psExtent, int bForce );
                  ^
ogrelasticlayer.cpp:3513:83: error: within this context
         const auto eRet = OGRLayer::GetExtentInternal(iGeomField, psExtent, bForce);
                                                                                   ^
make[3]: *** [../o/ogrelasticlayer.o] Error 1
make[3]: Leaving directory `/build/gdal/ogr/ogrsf_frmts/elastic'
```

**Comment by danielklim** [comment]
Just saw your comment on: https://github.com/OSGeo/gdal/issues/3374

Guess it's an upstream GDAL issue =/

**Comment by furick1** [comment]
does this help
[Dockerfile.txt](https://github.com/developmentseed/geolambda/files/5846022/Dockerfile.txt)

**Comment by matthewhanson** [comment]
@danielklim yeah, I was stopped by that GDAL issue and haven't revisited this since.   I'll check out the Dockerfile @furick1 posted.

**Pull request merged**
