### PR TITLE
Bump dependencies

### LINKED ISSUE #60: Library version updates
Ongoing issue to track changes to included library versions. When there's sufficient changes we will cut a new release.

### PR DESCRIPTION
**Pull request by robertd**
Closes #60

### CODE REVIEW

**Comment by robertd** [comment]
I've updated everything that's listed in #60. Hopefully there are no regression bugs :).

**Comment by robertd** [comment]
I spoke too soon. It looks like libgeotiff 1.5.1 introduced a bug, so I had to revert back to 1.5.0.

```
docker run --rm -v $PWD:/home/geolambda -it geolambda-test:${VERSION} package.sh
Creating deploy package
rsync: link_stat "/usr/local/share/gdal" failed: No such file or directory (2)
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1039) [sender=3.0.6]
```

**Comment by robertd** [comment]
After some digging around it seems that bug has been introduced in either [this](https://github.com/OSGeo/libgeotiff/commit/f4956251737b29ccc3f6366cd5b21520689f21d9) or [this](https://github.com/OSGeo/libgeotiff/commit/95b8bb4b4cbaae1cafe8b78aee8e655978dd4fea) commit, or both...  https://github.com/OSGeo/libgeotiff/commits/1.5.1

Unfortunately I'm not very familiar with libgeotiff repo. Perhaps, this warrants an issue over at https://github.com/OSGeo/libgeotiff .

**Comment by robertd** [comment]
One of these updated dependencies is breaking python bindings lambda layer creation.

```
 ---> Running in d8bbbc263358
Collecting numpy (from -r requirements-pre.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/35/d5/4f8410ac303e690144f0a0603c4b8fd3b986feb2749c435f7cdbb288f17e/numpy-1.16.2-cp36-cp36m-manylinux1_x86_64.whl (17.3MB)
Installing collected packages: numpy
Successfully installed numpy-1.16.2
Collecting GDAL==2.4.0 (from -r requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/7c/b0/a2ecb10a68a319910c4681f452c83843b99c4ef6231d33a8e55b0104a50c/GDAL-2.4.0.tar.gz (564kB)
    Complete output from command python setup.py egg_info:
    running egg_info
    creating pip-egg-info/GDAL.egg-info
    writing pip-egg-info/GDAL.egg-info/PKG-INFO
    writing dependency_links to pip-egg-info/GDAL.egg-info/dependency_links.txt
    writing top-level names to pip-egg-info/GDAL.egg-info/top_level.txt
    writing manifest file 'pip-egg-info/GDAL.egg-info/SOURCES.txt'
    warning: manifest_maker: standard file '-c' not found

    Traceback (most recent call last):
      File "/tmp/pip-install-gl9lobo0/GDAL/setup.py", line 151, in fetch_config
        p = subprocess.Popen([command, args], stdout=subprocess.PIPE)
      File "/root/.pyenv/versions/3.6.1/lib/python3.6/subprocess.py", line 707, in __init__
        restore_signals, start_new_session)
      File "/root/.pyenv/versions/3.6.1/lib/python3.6/subprocess.py", line 1326, in _execute_child
        raise child_exception_type(errno_num, err_msg)
    FileNotFoundError: [Errno 2] No such file or directory: '../../apps/gdal-config'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/tmp/pip-install-gl9lobo0/GDAL/setup.py", line 237, in get_gdal_config
        return fetch_config(option, gdal_config=self.gdal_config)
      File "/tmp/pip-install-gl9lobo0/GDAL/setup.py", line 154, in fetch_config
        raise gdal_config_error(e)
    __main__.gdal_config_error: [Errno 2] No such file or directory: '../../apps/gdal-config'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/tmp/pip-install-gl9lobo0/GDAL/setup.py", line 151, in fetch_config
        p = subprocess.Popen([command, args], stdout=subprocess.PIPE)
      File "/root/.pyenv/versions/3.6.1/lib/python3.6/subprocess.py", line 707, in __init__
        restore_signals, start_new_session)
      File "/root/.pyenv/versions/3.6.1/lib/python3.6/subprocess.py", line 1326, in _execute_child
        raise child_exception_type(errno_num, err_msg)
    FileNotFoundError: [Errno 2] No such file or directory: 'gdal-config'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-gl9lobo0/GDAL/setup.py", line 430, in <module>
        setup(**setup_kwargs)
      File "/root/.pyenv/versions/3.6.1/lib/python3.6/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/root/.pyenv/versions/3.6.1/lib/python3.6/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/root/.pyenv/versions/3.6.1/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/root/.pyenv/versions/3.6.1/lib/python3.6/site-packages/setuptools/command/egg_info.py", line 279, in run
        self.find_sources()
      File "/root/.pyenv/versions/3.6.1/lib/python3.6/site-packages/setuptools/command/egg_info.py", line 306, in find_sources
        mm.run()
      File "/root/.pyenv/versions/3.6.1/lib/python3.6/site-packages/setuptools/command/egg_info.py", line 533, in run
        self.add_defaults()
      File "/root/.pyenv/versions/3.6.1/lib/python3.6/site-packages/setuptools/command/egg_info.py", line 562, in add_defaults
        sdist.add_defaults(self)
      File "/root/.pyenv/versions/3.6.1/lib/python3.6/site-packages/setuptools/command/py36compat.py", line 36, in add_defaults
        self._add_defaults_ext()
      File "/root/.pyenv/versions/3.6.1/lib/python3.6/site-packages/setuptools/command/py36compat.py", line 119, in _add_defaults_ext
        build_ext = self.get_finalized_command('build_ext')
      File "/root/.pyenv/versions/3.6.1/lib/python3.6/distutils/cmd.py", line 299, in get_finalized_command
        cmd_obj.ensure_finalized()
      File "/root/.pyenv/versions/3.6.1/lib/python3.6/distutils/cmd.py", line 107, in ensure_finalized
        self.finalize_options()
      File "/tmp/pip-install-gl9lobo0/GDAL/setup.py", line 287, in finalize_options
        self.gdaldir = self.get_gdal_config('prefix')
      File "/tmp/pip-install-gl9lobo0/GDAL/setup.py", line 243, in get_gdal_config
        return fetch_config(option)
      File "/tmp/pip-install-gl9lobo0/GDAL/setup.py", line 154, in fetch_config
        raise gdal_config_error(e)
    __main__.gdal_config_error: [Errno 2] No such file or directory: 'gdal-config'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-gl9lobo0/GDAL/
The command '/bin/sh -c pip install -r requirements-pre.txt;     pip install -r requirements.txt' returned a non-zero code: 1
```

I've updated PR name with `[WIP]` suffix, as I will be updating one dependency at a time to isolate the issue.

**Comment by robertd** [comment]
Disregard my commend above. My docker got wonky somehow. Removing [WIP] prefix. Please test before merging. Issue with `libgeotiff 1.5.1` still stands.

**Comment by matthewhanson** [comment]
@robertd Thanks for doing all this legwork and getting the versions updated.  I will build and test the image tomorrow and merge.

**Comment by robertd** [comment]
@matthewhanson You're welcome!

**Pull request merged**
